variables:
  IMAGE_NAME: gitlab-gke
  CLUSTER_ZONE: us-central1-b
  GCP_PROJECT_ID: pv-lb-test
  CLUSTER_NAME: kubernetes-testing-cluster
  
services:
  - docker:dind
  
stages:
  - publish
  - deploy

publish-image:
  stage: publish
  image: dwdraju/alpine-gcloud
  script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit --config=cloudbuild.yaml
  only:
    - master