# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay
  GCP_PROJECT_ID: cicd-testing-273606
  IMAGE_NAME: hack-tom/cicd-testing-273606:v1.0

services:
- docker:apline:3.11.5

stages:
  - test
  - publish

tests:
  image: python:3.7
  stage: test
  script:
    - python test.py
  tags:
    - docker

publish-image:
  stage: publish
  script:
    - docker build -t $IMAGE_NAME dockerfiles/
    - docker run gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME
    - docker tag gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME
    - docker push gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:latest