# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay
  GCP_PROJECT_ID: cicd-testing-273606
  IMAGE_NAME: cicd-testing-273606:latest
  VERSION: v1.0

image: docker:git

services:
  - docker:dind
  
stages:
#  - test
  - build
  - run
#  - publish

#tests:
#  stage: test
#  script:
#    - python test.py
#  tags:
#    - docker

build-image:
  stage: build
  script:
    - docker build -t gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME} .
    - mkdir image
    - docker save gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME} > image/app.tar
  artifacts:
    paths:
      - image

run-image:
  stage: run
  script:
    - docker load -i image/app.tar
    - docker run --name app -d -p 5000:5000 -t gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME} .
  artifacts:
    paths:
      - image
    
publish-image:
  stage: publish
  image: gcr.io/cloud-builders/gke-deploy
  script:
    - run --filename=kubernetes/configuration.yaml --location=europe-west3-b --cluster=kubernetes-testing-cluster
    - google-cloud-sdk/bin/gcloud builds submit --project=gcr.io/${GCP_PROJECT_ID} --config cloudbuild.yaml
#  artifacts:
 #   paths:
  #    - image
#    - kubectl  run dataservice --image=gcr.io/${GCP_PROJECT_ID}/data_service:v1 --port 80
#    - kubectl  run apiservice --image=gcr.io/${GCP_PROJECT_ID}/api_service:v1 --port 80
#    - kubectl  expose deployment dataservice --type=ClusterIP
#    - kubectl  expose deployment apiservice --type=LoadBalancer
