# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay
  GCP_PROJECT_ID: cicd-testing-273606
  IMAGE_NAME: hack-tom/cicd-testing-273606:v1.0

image: gitlab/dind

services:
  - docker:dind
  
stages:
#  - test
  - build
  - publish

#tests:
#  stage: test
#  script:
#    - python test.py
#  tags:
#    - docker

build-image:
  stage: build
  script:
    - docker build -t gcr.io/${PROJECT_ID}/data_service:v1 .
    - docker build -t gcr.io/${PROJECT_ID}/api_service:v1 .

publish-image:
  stage: publish
  script:
    - docker push gcr.io/${PROJECT_ID}/data_service:v1
    - docker push gcr.io/${PROJECT_ID}/api_service:v1
    - gcloud container clusters create mediumtuts-cluster --num-nodes=2 --zone=us-central1-b
    - kubectl  run dataservice --image=gcr.io/${PROJECT_ID}/data_service:v1 --port 80
    - kubectl  run apiservice --image=gcr.io/${PROJECT_ID}/api_service:v1 --port 80
    - kubectl  expose deployment dataservice --type=ClusterIP
    - kubectl  expose deployment apiservice --type=LoadBalancer

