# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay
  GCP_PROJECT_ID: cicd-testing-273606
  IMAGE_NAME: cicd-testing-273606:latest
  VERSION: v1.0

image: docker:git

services:
  - docker:dind
  
stages:
#  - test
  - build
  - run
  - publish

#tests:
#  stage: test
#  script:
#    - python test.py
#  tags:
#    - docker

build-image:
  stage: build
  script:
    - docker build -t gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME} .
    - mkdir image
    - docker save gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME} > image/app.tar
  artifacts:
    paths:
      - image

run-image:
  stage: run
  script:
    - docker load -i image/app.tar
    - docker run --name app -d -p 80:80 -t gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME} .
    - kubectl  run cicd-testing --image=gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME} --port 5000
    - kubectl  expose deployment cicd-testing --type=ClusterIP

  artifacts:
    paths:
      - image
    
