# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay
  GCP_PROJECT_ID: cicd-testing-273606
  IMAGE_NAME: hack-tom/cicd-testing-273606:v1.0

services:
- docker:apline:3.11.5

stages:
  - test
  - build
  - publish

tests:
  image: python:3.7
  stage: test
  script:
    - python test.py
  tags:
    - docker

before_script:
  script:
    - apt-get update
    - apt-get install python-dev python-pip git docker.io

build-image:
  stage: build
  script:
    - docker build -t cicd-testing .
    - docker images

publish-image:
  stage: publish
  script:
    - docker run -p 80:80 -t cicd-testing
