# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay
  GCP_PROJECT_ID: stoked-mode-274115
  IMAGE_NAME: cicd-testing:latest
  VERSION: v1.0

image: docker:git

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

services:
  - docker:dind
 
stages:
#  - test
  - build
  - run
  - publish

#tests:
#  stage: test
#  script:
#    - python test.py
#  tags:
#    - docker

build-image:
  stage: build
  script:
    - docker build -t ${GCP_PROJECT_ID}/${IMAGE_NAME} .
    - docker push ${GCP_PROJECT_ID}/${IMAGE_NAME}

run-image:
  stage: run
  script: 
    - docker pull ${GCP_PROJECT_ID}/${IMAGE_NAME}
    - docker run --entrypoint="/bin/bash" -d --expose=5000 ${GCP_PROJECT_ID}/${IMAGE_NAME}
    - docker ps
    - docker exec ${GCP_PROJECT_ID}/${IMAGE_NAME} "export FLASK_APP=app && flask run"
    #- kubectl run --image=gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME} --port 5000
    #- kubectl  expose deployment app --type=ClusterIP  
  environment:
    name: kubernetes-testing-cluster
    url: 35.193.216.125.nip.io
    kubernetes:
        namespace: kubernetes-testing-cluster
  artifacts:
    paths:
      - image
