# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA

image: docker:git

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

services:
  - docker:dind
 
stages:
#  - test
  - build
  - run

#tests:
#  stage: test
#  script:
#    - python test.py
#  tags:
#    - docker

build-image:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME

run-image:
  stage: run
  script: 
    - docker pull $DOCKER_IMAGE_NAME
    - docker run --name=app -d -p=5000:5000 -t $DOCKER_IMAGE_NAME 
    - docker ps
    - docker exec app "export FLASK_APP=app && flask run"
    #- kubectl run --image=gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME} --port 5000
    #- kubectl  expose deployment app --type=ClusterIP  
  environment:
    name: kubernetes-testing-cluster
    url: 35.193.216.125.nip.io
    kubernetes:
        namespace: kubernetes-testing-cluster
  artifacts:
    paths:
      - image
