# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay
  GCP_PROJECT_ID: cicd-testing-273606
  IMAGE_NAME: hack-tom/cicd-testing-273606:v1.0

image: gitlab/dind

services:
  - docker:dind
  
stages:
#  - test
  - build
  - publish

#tests:
#  stage: test
#  script:
#    - python test.py
#  tags:
#    - docker

build-image:
  stage: build
  script:
    - "docker build -t cicd-testing ."
    - "docker images"

publish-image:
  stage: publish
  script:
    - "docker run -p 80:80 --privileged=true -t cicd-testing"
