steps:
#clone the code from google cloud source repository
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://gitlab.com/hack-tom/cicd-testing.git']

#build the image
 - name: 'gcr.io/cloud-builders/docker'
  args: ['build', 'gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}', '.']

#push the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']

#update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/${_DEPLOYMENTNAME}'
    - '${_DEPLOYMENTNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLOUSTER=${_GKE_CLUSTER}'

substitutions:
  #GCP Specific Configuration
  _PROJECT: playing-with-cicd
  _ZONE: us-central1-c
  _GKE_CLUSTER: kubernetes-testing-cluster

  #repository specific config / DevOps can change
  _DEPLOYMENTNAME: cicd-testing
  _CONTAINERNAME: cicd-testing
  _REPO_NAME: cicd-testing

  #version info / developers only change
  _VERSION: v1.0

options:
  substitution_option: 'ALLOW_LOOSE'
