variables:
  DOCKER_DRIVER: overlay
  GCP_PROJECT_ID: cicd-testing-273606
  IMAGE_NAME: cicd-testing-273606:v1.0
  VERSION: latest

steps:
...
#tests
- name: test
  args:
    - python test.py
- name: build
  args:
    - docker build -t gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME} .
    - docker push gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME} 
# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernetes-config-file
  - --image=gcr.io/${GCP_PROJECT_ID}/${IMAGE_NAME}
  - --location=$europe-west3-b
  - --cluster=kubernetes-testing-cluster