steps:
...
# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernetes-config-file
  - --image=gcr.io/cicd-testing-273606/cicd-testing
  - --location=europe-west3-b
  - --cluster=kubernetes-testing-cluster