clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://34.89.161.248
  name: gke_cicd-testing-273606_europe-west3-b_kubernetes-testing-cluster
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://34.71.74.201
  name: gke_playing-with-cicd_us-central1-c_kubernetes-testing-cluster
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://34.71.74.201
  name: gke_playing-with-cicd_us-central1-c_kubernetes-testing-cluster
contexts:
- context:
    cluster: gke_cicd-testing-273606_europe-west3-b_kubernetes-testing-cluster
    user: gke_cicd-testing-273606_europe-west3-b_kubernetes-testing-cluster
  name: gke_cicd-testing-273606_europe-west3-b_kubernetes-testing-cluster
- context:
    cluster: gke_playing-with-cicd_us-central1-c_kubernetes-testing-cluster
    user: gke_playing-with-cicd_us-central1-c_kubernetes-testing-cluster
  name: gke_playing-with-cicd_us-central1-c_kubernetes-testing-cluster
current-context: gke_cicd-testing-273606_europe-west3-b_kubernetes-testing-cluster
kind: Config
preferences: {}
users:
- name: gke_cicd-testing-273606_europe-west3-b_kubernetes-testing-cluster
  user:
    auth-provider:
      config:
        access-token: ya29.a0Ae4lvC0g8TCrnZFDBsneq1h0JPxeg7wo8WyA04qkqM99-8-ilRlt3L_nqyOsHWt3oYUo9p602xoMEUXJzlc1z4xszbZD0nmKSCo0FZAm8RNd6_55kyKBWmbSShsTqYrdVwMpvTCX5I7AcFDgi4AHUybcuNGKG1X_0W7T9
prNqDFLLax3QRVdJ_8ScoT0brKsoZtqth-Od-05UcoUH1oWtBxedIScmmyWEQzZcrbGriOznd7o6wTFjGbAo0mZ0tOQxeXZikXTiLtCRQ
        cmd-args: config config-helper --format=json
        cmd-path: /google/google-cloud-sdk/bin/gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: gke_playing-with-cicd_us-central1-c_kubernetes-testing-cluster
  user:
    auth-provider:
      config:
        access-token: ya29.a0Ae4lvC2t-7Le5_KPKcRQKCURyZOS1kqqvVbRGP-PSBeF1B85oHsTZBgv2F2O61_Z6aX
q1QVnHuzQusJBaYCdEyWla7yzIzaoUVp6N73pE7zpQQrJpi_WJVFmCtkiAPJQAe8EPCWiujM9DnnvXFQm-45S7vGUS7_pryc
l0xTpT4MPZgtnqB2jV5JPAqSO6H_qKO-JI1IUp5h3bfJglg5CUQ_QJY7RVadECWizrY0Jg9zdJE_0h7Zq4LWy6hAxVlWHukb
e2mVUUsZi
        cmd-args: config config-helper --format=json
        cmd-path: /google/google-cloud-sdk/bin/gcloud
        expiry: "2020-04-07T01:03:36Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp